insert into games (nome, imagem, preco, secao_id,descricao) values ('God of war','Assets/img/webp/god of war.webp', 99.90,2, 'É um novo começo para Kratos. Vivendo como um homem longe da sombra dos deuses, ele se aventura pelas selvagens florestas nórdicas com seu filho Atreus, lutando para cumprir uma missão profundamente pessoal.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('The last of us 2', 'Assets/img/webp/thelast.webp', 135.90,2, 'Cinco anos depois da jornada perigosa pelos Estados Unidos pós-pandêmicos, Ellie e Joel se estabelecem em Jackson, Wyoming. A vida em uma próspera comunidade de sobreviventes lhes trouxe paz e estabilidade, apesar da ameaça constante dos infectados e de outros sobreviventes mais desesperados. Quando um evento violento interrompe essa paz, Ellie embarca em uma jornada implacável para fazer justiça e encontrar uma solução. Enquanto vai atrás de cada um dos responsáveis, ela se confronta com as repercussões físicas e emocionais devastadoras de suas ações.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('Watch Dogs Legion', 'Assets/img/webp/whatdogs legion.webp', 39.90,1, 'Está na hora de retomar Londres, e você pode recrutar qualquer pessoa à sua vista para a sua resistência. Oportunistas corruptos estão no controle e cabe a você criar uma resistência para devolver a cidade para o povo. Com uma população inteira de potenciais recrutas e a tecnologia da cidade na ponta dos seus dedos, você precisará realizar hacks, infiltrar e lutar para liberar Londres. Bem-vindo à Resistência.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('Forza Horizon 5', 'Assets/img/webp/forza.webp', 159.90,1, 'Sua Aventura Definitiva de Horizon o aguarda! Explore as paisagens do mundo aberto vibrante e em constante evolução do México, com uma ação de direção divertida e ilimitada em centenas dos melhores carros do mundo.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('Dying Light','Assets/img/webp/dying light.webp',39.90, 2, 'O vírus venceu e a civilização sucumbiu à Era das Trevas. A cidade, uma das últimas grandes colônias humanas, está à beira do colapso. Use sua agilidade e suas habilidades de combate para sobreviver e reconstruir o mundo. Suas escolhas importam.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('CyberPunk', 'Assets/img/webp/cyberPunk.webp', 39.90, 2, 'Cyberpunk 2077 é uma história de ação e aventura de mundo aberto ambientada em Night City, uma megalópole obcecada por poder, glamour e biomodificações. Você joga como V, um mercenário fora da lei atrás de um implante único que carrega a chave da imortalidade. Você pode personalizar aparatos cibernéticos, conjunto de habilidades e estilo de jogo do personagem e explorar uma vasta cidade onde as decisões tomadas definem a história e o mundo ao seu redor.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('BF 2042 - PS5', 'Assets/img/webp/bf2042ps5.webp', 179.91, 2, 'Num futuro próximo mergulhado no caos, adapta-se e supera em campos de batalha dinâmicos com a ajuda do teu esquadrão e de um arsenal de ponta. Com suporte para até 128 jogadoresnos consoles de nova geração (geração antiga 64 jogadores), Battlefield 2042 traz consigo uma escala sem precedentes em vastos campos de batalha globais.');
insert into games (nome, imagem, preco, secao_id,descricao) values ('Days Gone', 'Assets/img/webp/daysgone.webp', 59.80, 2, 'Days Gone é um jogo de mundo aberto com zumbis em um cenário pós-apocalíptico jogado em uma perspectiva de terceira-pessoa. Os jogadores controlam Deacon St. John, um viajante e caçador de recompensas que prefere viver uma vida perigosa na estrada, ao invés da vida nos acampamentos na floresta.');

insert into videos (Path_video, Path_background, Path_Person, Path_logo) values ('./Assets/vid/godofwar.mp4#t8,100', './Assets/img/montanha.jpg','./Assets/img/persons/kratos.png', './Assets/img/logoGame.png');
insert into videos (Path_video, Path_background, Path_Person, Path_logo) values ('./Assets/vid/thelast2.mp4#t8,100', './Assets/img/scenaryTheLast.jpg','./Assets/img/persons/thelast.png', './Assets/img/tlouLogo.png');
insert into videos (Path_video, Path_background, Path_Person, Path_logo) values ('./Assets/vid/haloinfinite.mp4#t8,100', './Assets/img/halo-background.webp','./Assets/img/persons/helo.png', './Assets/img/halo-logo.png');

insert into sessao(id, sessao) values (1,'xbox');
insert into sessao(id, sessao) values (2,'playstion');
insert into sessao(id, sessao) values (3,'nintendo');
insert into sessao(id, sessao) values (4,'pc');

